# module imports
import random

# item imports
from copy import deepcopy

# local item imports
from action import Action
from dataclasses import dataclass
from tile import Tile
from bombTile import BombTile


@dataclass
class Adversary:
    # helper method for finding all empty tiles
    def getEmpty(self, state:GameState) -> list:
        #iterate to find all board spaces are None
        emptyCells = [
            (rowIdx, colIdx)
            for rowIdx in range(state.n)
            for colIdx in range(state.n)
            if state.board[rowIdx][colIdx] is None
        ]

        # skip adding if board is full
        if len(emptyCells) == 0:
            return []
        return emptyCells


    #helper method: checks if same value tile exists in the same row/column
    #if yes, then increment numConflicts
    def checkMerge(self, state:GameState, tile: Tile) -> int:
        value = tile.value
        location = tile.location
        numConflicts = 0
        # state.

        #check all values in same column
        for r in range(0, state.n):
            if state.board[r][tile.col] is not None :

                if state.board[r][tile.col].value == value and r != tile.row:
                    numConflicts+=1

        for c in range(0, state.n):
            if state.board[tile.row][c] is not None :
                if state.board[tile.row][c].value == value and c != tile.col:
                    numConflicts+=1

        return numConflicts

    #helper method for manhattan distance in clutterFactor
    def manhattanDistance(self, xy1, xy2):
        "Returns the Manhattan distance between points xy1 and xy2"
        return abs(xy1[0] - xy2[0]) + abs(xy1[1] - xy2[1])

    #returns sum of manhattan distance to every other tile on board
    #iterate through all tile spaces on board.
    # if the board space is not None, then find manhattan distance and add it to the total
    def clutterFactor(self, state:GameState, tile:Tile) -> int:
        location = tile.location
        clutterSum = 0
        for rowIdx in range(state.n):
            for colIdx in range(state.n):
                if state.board[rowIdx][colIdx] is not None:
                    clutterSum += self.manhattanDistance((tile.row, tile.col), (rowIdx, colIdx))
        return clutterSum


    #returns list of tuples:(probabilities, states)
    #probabilities are calculated through the clutterFactor and checkMerge factors
    def generateSuccessors(self, state: GameState , value:int ) -> list[tuple[float, GameState]]:

        state = deepcopy(state)
        emptyCells = self.getEmpty(state)
        options = {}
        lowest = -1
        clutterOptions = []

        # skip adding if board is full
        if len(emptyCells) == 0:
            return state

        #for each empty cell, calculate the "probability" to place a tile in that space
        #current weighting is through 1 - (number of merge conflicts + clutterfactor/n)
        #this can be changed very easily
        for cell in emptyCells:
            tile = Tile(value, cell[0], cell[1])
            # options[(cell[0], cell[1])] = (self.checkMerge(state, tile) + (self.clutterFactor(state, tile) / (state.n*state.n)))
            options[(cell[0], cell[1])] = 1 - (self.checkMerge(state, tile)/ (state.n) + (self.clutterFactor(state, tile) / (state.n*state.n)))

            #print("score?",  options[(cell[0], cell[1])])

        returnList = []

        #for every space in board:
        #if the space DOES contain a tile, then we cannot place a new tile there and pair it with a '0' probability
        #else, add a tile to the empty space, along with the probability calculated above
        for rowIdx in range(state.n):
            for colIdx in range(state.n):
                if state.board[rowIdx][colIdx] is not None:
                    #zero probability to place tile in spot that already has tile
                    returnList.append((0, state))
                else:
                    if value < 0:
                        tile = BombTile(value, rowIdx, colIdx)
                    else:
                        tile = Tile(value, rowIdx, colIdx)
                    stateCopy = deepcopy(state)
                    if value < 0:
                         stateCopy.board[rowIdx][colIdx] = BombTile(value=value, row=rowIdx, col=colIdx)
                    else:
                        stateCopy.board[rowIdx][colIdx] = Tile(value=value, row=rowIdx, col=colIdx)
                    #using values stored in a dictionary from the empty cell probabilities calculations
                    returnList.append((options[tile.row, tile.col], stateCopy))
        # print(returnList)
        return returnList


    # method that decides where to place the tile based on all states generated by the successors method
    def getPlacement(self, state: GameState, domain: list[int]) -> GameState:
        state = deepcopy(state)
        emptyCells = self.getEmpty(state)

        # skip adding if board is full
        if len(emptyCells) == 0:
            return state

        choices = []
        actualChoices = []
        #choices of tile values to place in the game
        tileValueChoices = domain
        #generates successors for each option. this can be changed with the length of tileValueChoices
        for value in tileValueChoices:
            choices.extend(self.generateSuccessors(state, value))

        #essentially filters out the zero/lower ranked scores
        for choice in choices:
            #if the probability in the gamestate to place tile is not zero
            if choice[0] != 0 or choice[0] != 0.0:
                #if probability score is greater than 0, then append it to the list of actual options to choose placement
                #if choice[0] > 0:
                actualChoices.append(choice)


        #if all choices are empty (essentially full board)
        if len(actualChoices) == 0:
            return choices[0][1]

        else:
            #sort the options
            temp = sorted(actualChoices, key=lambda x: x[0], reverse=True) #actualChoices.sort(key=lambda x: x[0], reverse=True) #[:(len(actualChoices)/2)]
            #select random from the top k = actual choices /2
            rand = random.randrange(0, int(len(temp)/2))
            return temp[rand][1]


# @dataclass(init=False)
# class DummyAdversary(Adversary):
#     def generateSuccessors(self, state: GameState) -> list[tuple[float, GameState]]:
#         raise NotImplementedError

#     def getPlacement(self, state: GameState) -> GameState:
#         # create copy of state
#         state = deepcopy(state)

#         # get all empty cells
#         emptyCells = [
#             (rowIdx, colIdx)
#             for rowIdx in range(state.n)
#             for colIdx in range(state.n)
#             if state.board[rowIdx][colIdx] is None
#         ]

#         # skip adding if board is full
#         if len(emptyCells) == 0:
#             return state

#         # pick random cell
#         rowIdx, colIdx = random.choice(emptyCells)

#         # place a block from the domain here
#         state.board[rowIdx][colIdx] = Tile(value=2, row=rowIdx, col=colIdx)

#         return state


@dataclass(init=False)
class GameState:
    """
    Represents any one state of the 2048 game.
    """

    #
    # fields
    #

    board: list[list[Tile | None]]
    """
    Nested lists containing the tile objects.
    """

    score: int
    """
    Total score of the current board.
    """

    n: int
    """
    Size of the NxN board.
    """
    
    domain: list[int]
    """
    The possible values of tiles that can be added. 
    """
    
    #
    # dynamic properties
    #

    @property
    def emptySpaces(self) -> int:
        """
        Number of empty spaces on the board.
        """
        count: int = 0
        for row in self.board:
            for tile in row:
                if tile is None:
                    count += 1
        return count

    #
    # constructors
    #

    def __init__(self, n: int) -> None:
        """
        Default initializer. Instantiates all class variables for a empty
        GameState of size n.
        """
        # Create original list
        self.board = list()
        for i in range(n):
            # Add n empty lists to each list in list
            self.board.append(list())
            for _ in range(n):
                self.board[i].append(None)

        # instance vars
        self.score = 0
        self.n = n
        self.domain = [-1, 2, 4]

    @staticmethod
    def startState(n: int, adversary: Adversary) -> GameState:
        """
        Create a new random start state.
        """
        state = GameState(n)
        state = adversary.getPlacement(state, state.domain)
        return state

    #
    # api methods
    #

    def generateSuccessors(self,adversary: Adversary) -> dict[Action, list[tuple[float, GameState]]]:
        successors = {}

        #Loop through each legal action
        for action in self.getLegalActions():
            #Create a new state without placing a tile
            newState = self._copy()
            newState = newState._move(action)


            successors[action] = adversary.generateSuccessors(newState, 2)

        #After creating distributions for each action, return
        return successors

    def takeTurn(self, action: Action, adversary: Adversary) -> GameState:
        """
        Generate a new GameState from a given action. New tile(s) are then
        placed by the given adversary.
        """

        newState = self._move(action)

        if newState == self:
            return self

        # add tile
        #print("Self.domain = " + str(self.domain))
        newState = adversary.getPlacement(newState, self.domain)

        #print("GameState = ")
        #newState.printGameState()

        return newState

    def isLoss(self) -> bool:
        if self.emptySpaces != 0:
            return False

        return (len(self.getLegalActions()) == 0)


    def getLegalActions(self) -> list[Action]:
        legalActions: list[Action] = []

        for action in Action:
            #print("Checking action" + str(action))
            tempState = self._move(action)
            if tempState != self:
                legalActions.append(action)


        #print("LegalActions = " + str(legalActions))
        return legalActions

    def printGameState(self) -> None:
        print("Current score = " + str(self.score))
        for i in range(len(self.board[0])):
            for tile in self.board[i]:
                print(" | " + str(tile) + " | \t", end="")
            print('')

    def __eq__(self, state: object) -> bool:
        if state is None:
            return False

        if not isinstance(state, GameState):
            raise TypeError("Can only compare GameStates to other GameStates")

        if self.score != state.score:
            return False

        for rowIndex, row in enumerate(self.board):
            for colIndex, tile in enumerate(row):
                if tile != state.board[rowIndex][colIndex]:
                    return False

        return True

    #
    # helper methods
    #
    def _move(self, action: Action) -> GameState:
        """
        Updates the board without adding a new tile
        """
        # create copy of new state
        newState = self._copy()

        # merge based on action
        match action:
            case Action.UP:
                for colIdx in range(newState.n):
                    # generate col
                    col = [newState.board[rowIdx][colIdx] for rowIdx in range(newState.n)]

                    # merge
                    col, addScore = GameState._mergeLine(col)

                    # write back to grid
                    newState.score += addScore
                    for rowIdx in range(newState.n):
                        newState.board[rowIdx][colIdx] = col[rowIdx]
            case Action.DOWN:
                for colIdx in range(newState.n):
                    # generate reverse col
                    col = [newState.board[rowIdx][colIdx] for rowIdx in range(newState.n)]
                    col.reverse()

                    # merge and reverse
                    col, addScore = GameState._mergeLine(col)
                    col.reverse()

                    # write back to grid in reverse
                    newState.score += addScore
                    for rowIdx in range(newState.n):
                        newState.board[rowIdx][colIdx] = col[rowIdx]
            case Action.LEFT:
                for rowIdx in range(newState.n):
                    # generate row
                    row = [newState.board[rowIdx][colIdx] for colIdx in range(newState.n)]

                    # merge
                    row, addScore = GameState._mergeLine(row)

                    # write back to grid
                    newState.score += addScore
                    for colIdx in range(newState.n):
                        newState.board[rowIdx][colIdx] = row[colIdx]
            case Action.RIGHT:
                for rowIdx in range(newState.n):
                    # generate reverse row
                    row = [newState.board[rowIdx][colIdx] for colIdx in range(newState.n)]
                    row.reverse()

                    # merge and reverse
                    row, addScore = GameState._mergeLine(row)
                    row.reverse()

                    # write back to grid
                    newState.score += addScore
                    for colIdx in range(newState.n):
                        newState.board[rowIdx][colIdx] = row[colIdx]

        # update locations
        for rowIdx in range(newState.n):
            for colIdx in range(newState.n):
                # get tile
                tile = newState.board[rowIdx][colIdx]
                if tile is None:
                    continue

                # update tile
                tile.location = (rowIdx, colIdx)

        #print("GameState = ")
        #newState.printGameState()

        return newState


    def _copy(self) -> GameState:
        """
        Create another instance of GameState from this GameState.
        """
        return deepcopy(self)

    @staticmethod
    def _mergeLine(line: list[Tile | None]) -> tuple[list[Tile | None], int]:
        """
        Merge tiles in line and return the new line and the amount of score
        gained.
        """

        # derive values
        n = len(line)
        score = 0

        # remove empty blocks
        line = [tile for tile in line if tile is not None]
        
        print("Line = " + str(line))
        
        hasBomb: bool = False
        for tile in line:
            #Add extra special tile types here if we add them
            print("Type(Tile) = " + str(type(tile)))
            if isinstance(tile, BombTile):
                hasBomb = True
                
        print("HasBomb = " + str(hasBomb))
                
        if hasBomb:
            print("Line before bombs = " + str(line))
            #All tiles before the bomb are deleted, and then so is the bomb
            # 4 _ Bomb 2
            
            # 4 Bomb 2
            
            # 2 
            
            # 2 _ _ _
            lastBombIndex = 0
            for i, tile in enumerate(reversed(line)):
                if type(tile) == BombTile and lastBombIndex != 0:
                    lastBombIndex = i
                #If we have found the last bombtile, remove the values of the removed tiles from score
                if type(tile) != BombTile and lastBombIndex != 0:
                    score -= tile.value
            
            #Remove the tiles before the bomb
            line = deepcopy(line[lastBombIndex:])
            
            print("Line after bombs = " + str(line))
        

        # merge adjacents
        for i in range(1, len(line)):
            if line[i - 1] is not None and line[i - 1].value == line[i].value:  # type: ignore
                newTile: Tile = deepcopy(line[i - 1])  # type: ignore
                newTile.value *= 2
                newTile.location = None
                line[i - 1] = newTile
                line[i] = None
                score += newTile.value

        # remove empty blocks again
        line = [tile for tile in line if tile is not None]

        # pad with empties
        for _ in range(n - len(line)):
            line.append(None)

        return (line, score)
